name-template: 'v$NEXT_MAJOR_VERSION'
tag-template: 'v$NEXT_MAJOR_VERSION'
version-template: '$MAJOR'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '💅🏻 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
template: |
  ## What’s Changed

  $CHANGES
