name: Pull Request
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-16-${{ hashFiles('package-lock.json') }}
          restore-keys: node-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-16-${{ hashFiles('package-lock.json') }}

      - name: Cache .nuxt
        uses: actions/cache@v3
        with:
          path: ./.nuxt
          key: saas-starter-${{ github.sha }}

      - name: Cache cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ui-cypress-^10.4.0

  lint_and_unit_tests:
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-16-${{ hashFiles('package-lock.json') }}

      - name: Cache .nuxt
        uses: actions/cache@v3
        with:
          path: ./.nuxt
          key: saas-starter-${{ github.sha }}

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: Component Tests
        run: npm run test:component

  build_docker:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
