name: 'Semantic Pull Request'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic_pull_request:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
